// Transcribed from docs/ft891-menus.md — do not edit by hand without
// updating the doc; MenuCatalogDocTests checks agreement.

enum CatalogItems {
    static let all: [MenuItem] =
        agc + display + dvs + keyer + general + modeAM + modeCW + modeDATA
        + modeFM + modeRTTY + modeSSB + rxDSP + scope + tuning + txAudio
        + txGeneral + reset + version

    // MARK: - TX AUDIO parametric-EQ frequency encodings (docs: 15-xx)

    /// `00` = OFF; `01`–`07` = 100–700 Hz in 100 Hz steps.
    private static let eq1Freq = MenuValueKind.options(
        ["OFF"] + stride(from: 100, through: 700, by: 100).map { "\($0) Hz" })
    /// `00` = OFF; `01`–`09` = 700–1500 Hz in 100 Hz steps.
    private static let eq2Freq = MenuValueKind.options(
        ["OFF"] + stride(from: 700, through: 1500, by: 100).map { "\($0) Hz" })
    /// `00` = OFF; `01`–`18` = 1500–3200 Hz in 100 Hz steps.
    private static let eq3Freq = MenuValueKind.options(
        ["OFF"] + stride(from: 1500, through: 3200, by: 100).map { "\($0) Hz" })

    // MARK: - 01 AGC

    private static let agc: [MenuItem] = [
        MenuItem(id: "01-01", group: .agc,
                 officialName: "AGC FAST DELAY",
                 friendlyName: "AGC fast decay time",
                 summary: "Hold-to-decay time of the AGC voltage when AGC is set to FAST.",
                 kind: .number(20...4000, step: 20, unit: "ms"),
                 digits: 4, defaultValue: 300),
        MenuItem(id: "01-02", group: .agc,
                 officialName: "AGC MID DELAY",
                 friendlyName: "AGC mid decay time",
                 summary: "Hold-to-decay time of the AGC voltage when AGC is set to MID.",
                 kind: .number(20...4000, step: 20, unit: "ms"),
                 digits: 4, defaultValue: 700),
        MenuItem(id: "01-03", group: .agc,
                 officialName: "AGC SLOW DELAY",
                 friendlyName: "AGC slow decay time",
                 summary: "Hold-to-decay time of the AGC voltage when AGC is set to SLOW.",
                 kind: .number(20...4000, step: 20, unit: "ms"),
                 digits: 4, defaultValue: 3000),
    ]

    // MARK: - 02 DISPLAY

    private static let display: [MenuItem] = [
        MenuItem(id: "02-01", group: .display,
                 officialName: "LCD CONTRAST",
                 friendlyName: "Display contrast",
                 summary: "Sets the LCD contrast level.",
                 kind: .number(1...15),
                 digits: 2, defaultValue: 8),
        MenuItem(id: "02-02", group: .display,
                 officialName: "DIMMER BACKLIT",
                 friendlyName: "Key backlight brightness",
                 summary: "Sets the brightness of the key LEDs.",
                 kind: .number(1...15),
                 digits: 2, defaultValue: 8),
        MenuItem(id: "02-03", group: .display,
                 officialName: "DIMMER LCD",
                 friendlyName: "LCD brightness",
                 summary: "Sets the brightness of the LCD backlight.",
                 kind: .number(1...15),
                 digits: 2, defaultValue: 8),
        MenuItem(id: "02-04", group: .display,
                 officialName: "DIMMER TX/BUSY",
                 friendlyName: "TX/BUSY LED brightness",
                 summary: "Sets the brightness of the TX/BUSY indicator.",
                 kind: .number(1...15),
                 digits: 2, defaultValue: 8),
        MenuItem(id: "02-05", group: .display,
                 officialName: "PEAK HOLD",
                 friendlyName: "Meter peak hold",
                 summary: "How long the meter holds its maximum reading.",
                 kind: .options(["OFF", "0.5 s", "1.0 s", "2.0 s"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "02-06", group: .display,
                 officialName: "ZIN LED",
                 friendlyName: "CW zero-in LED",
                 summary: "Enables the TX/BUSY LED as a CW tuning (zero-in) indicator.",
                 kind: .toggle,
                 digits: 1, defaultValue: 0),
        MenuItem(id: "02-07", group: .display,
                 officialName: "POP-UP MENU",
                 friendlyName: "Pop-up position",
                 summary: "Sets whether pop-up screens appear in the upper or lower display area.",
                 kind: .options(["UPPER", "LOWER"]),
                 digits: 1, defaultValue: 1),
    ]

    // MARK: - 03 DVS

    private static let dvs: [MenuItem] = [
        MenuItem(id: "03-01", group: .dvs,
                 officialName: "DVS RX OUT LVL",
                 friendlyName: "Voice memory monitor level",
                 summary: "Playback/monitoring volume of the recorded voice memories.",
                 kind: SharedEncoding.level100,
                 digits: 3, defaultValue: 50),
        MenuItem(id: "03-02", group: .dvs,
                 officialName: "DVS TX OUT LVL",
                 friendlyName: "Voice memory TX level",
                 summary: "Microphone-output (transmit) level of the voice memories.",
                 kind: SharedEncoding.level100,
                 digits: 3, defaultValue: 50),
    ]

    // MARK: - 04 KEYER

    private static let keyer: [MenuItem] = [
        MenuItem(id: "04-01", group: .keyer,
                 officialName: "KEYER TYPE",
                 friendlyName: "Keyer type",
                 summary: "Selects the electronic keyer emulation used with a paddle.",
                 kind: .options(["OFF", "BUG", "ELEKEY-A", "ELEKEY-B", "ELEKEY-Y", "ACS"]),
                 digits: 1, defaultValue: 3),
        MenuItem(id: "04-02", group: .keyer,
                 officialName: "KEYER DOT/DASH",
                 friendlyName: "Paddle polarity",
                 summary: "Normal or reversed dot/dash paddle connections.",
                 kind: .options(["NOR", "REV"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "04-03", group: .keyer,
                 officialName: "CW WEIGHT",
                 friendlyName: "CW weight",
                 summary: "Dot:dash weighting ratio of the built-in keyer.",
                 kind: .number(25...45),  // wire = displayed ratio × 10 (2.5–4.5)
                 digits: 2, defaultValue: 30),
        MenuItem(id: "04-04", group: .keyer,
                 officialName: "BEACON INTERVAL",
                 friendlyName: "Beacon repeat interval",
                 summary: "Repeat interval for CW beacon message transmission (OFF disables).",
                 kind: .number(0...690, unit: "s"),  // 0 = OFF; 1–240 in 1 s, 270–690 in 30 s
                 digits: 3, defaultValue: 0),
        MenuItem(id: "04-05", group: .keyer,
                 officialName: "NUMBER STYLE",
                 friendlyName: "Contest number style",
                 summary: "Morse \"cut number\" abbreviation style for the contest serial number.",
                 kind: .options(["1290", "AUNO", "AUNT", "A2NO", "A2NT", "12NO", "12NT"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "04-06", group: .keyer,
                 officialName: "CONTEST NUMBER",
                 friendlyName: "Contest serial number",
                 summary: "Current contest QSO serial number sent by the keyer.",
                 kind: .number(0...9999),
                 digits: 4, defaultValue: 1),
        MenuItem(id: "04-07", group: .keyer,
                 officialName: "CW MEMORY 1",
                 friendlyName: "CW memory 1 type",
                 summary: "Message keyer slot 1 stores typed TEXT or a paddle-recorded MESSAGE.",
                 kind: .options(["TEXT", "MESSAGE"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "04-08", group: .keyer,
                 officialName: "CW MEMORY 2",
                 friendlyName: "CW memory 2 type",
                 summary: "Same as 04-07 for slot 2.",
                 kind: .options(["TEXT", "MESSAGE"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "04-09", group: .keyer,
                 officialName: "CW MEMORY 3",
                 friendlyName: "CW memory 3 type",
                 summary: "Same as 04-07 for slot 3.",
                 kind: .options(["TEXT", "MESSAGE"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "04-10", group: .keyer,
                 officialName: "CW MEMORY 4",
                 friendlyName: "CW memory 4 type",
                 summary: "Same as 04-07 for slot 4.",
                 kind: .options(["TEXT", "MESSAGE"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "04-11", group: .keyer,
                 officialName: "CW MEMORY 5",
                 friendlyName: "CW memory 5 type",
                 summary: "Same as 04-07 for slot 5.",
                 kind: .options(["TEXT", "MESSAGE"]),
                 digits: 1, defaultValue: 0),
    ]

    // MARK: - 05 GENERAL

    private static let general: [MenuItem] = [
        MenuItem(id: "05-01", group: .general,
                 officialName: "NB WIDTH",
                 friendlyName: "Noise blanker width",
                 summary: "Blanking pulse duration for the noise blanker.",
                 kind: .options(["1 ms", "3 ms", "10 ms"]),
                 digits: 1, defaultValue: 1),
        MenuItem(id: "05-02", group: .general,
                 officialName: "NB REJECTION",
                 friendlyName: "Noise blanker rejection",
                 summary: "Attenuation depth applied to blanked noise.",
                 kind: .options(["10 dB", "30 dB", "50 dB"]),
                 digits: 1, defaultValue: 1),
        MenuItem(id: "05-03", group: .general,
                 officialName: "NB LEVEL",
                 friendlyName: "Noise blanker level",
                 summary: "Threshold level of the noise blanker.",
                 kind: .number(0...10),
                 digits: 2, defaultValue: 5),
        MenuItem(id: "05-04", group: .general,
                 officialName: "BEEP LEVEL",
                 friendlyName: "Beep volume",
                 summary: "Key-beep loudness.",
                 kind: SharedEncoding.level100,
                 digits: 3, defaultValue: 30),
        MenuItem(id: "05-05", group: .general,
                 officialName: "RF/SQL VR",
                 friendlyName: "RF/SQL knob function",
                 summary: "Selects whether the RF/SQL knob controls RF gain or squelch.",
                 kind: .options(["RF", "SQL"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "05-06", group: .general,
                 officialName: "CAT RATE",
                 friendlyName: "CAT baud rate",
                 summary: "Serial speed of the CAT interface.",
                 kind: .options(["4800 bps", "9600 bps", "19200 bps", "38400 bps"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "05-07", group: .general,
                 officialName: "CAT TOT",
                 friendlyName: "CAT timeout",
                 summary: "Time-out timer for incomplete CAT command input.",
                 kind: .options(["10 ms", "100 ms", "1000 ms", "3000 ms"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "05-08", group: .general,
                 officialName: "CAT RTS",
                 friendlyName: "CAT RTS handshake",
                 summary: "Enables monitoring of the host's RTS line on the CAT port.",
                 kind: .toggle,
                 digits: 1, defaultValue: 1),
        MenuItem(id: "05-09", group: .general,
                 officialName: "MEM GROUP",
                 friendlyName: "Memory groups",
                 summary: "Divides the 99 memories into 6 groups.",
                 kind: .toggle,
                 digits: 1, defaultValue: 0),
        MenuItem(id: "05-10", group: .general,
                 officialName: "FM SETTING",
                 friendlyName: "FM setting screen",
                 summary: "Shows/hides the FM SETTING function screen.",
                 kind: .toggle,
                 digits: 1, defaultValue: 0),
        MenuItem(id: "05-11", group: .general,
                 officialName: "REC SETTING",
                 friendlyName: "REC setting screen",
                 summary: "Shows/hides the REC SETTING function screen.",
                 kind: .toggle,
                 digits: 1, defaultValue: 0),
        MenuItem(id: "05-12", group: .general,
                 officialName: "ATAS SETTING",
                 friendlyName: "ATAS setting screen",
                 summary: "Shows/hides the ATAS manual-tuning function screen.",
                 kind: .toggle,
                 digits: 1, defaultValue: 0),
        MenuItem(id: "05-13", group: .general,
                 officialName: "QUICK SPL FREQ",
                 friendlyName: "Quick-split offset",
                 summary: "TX offset applied by the Quick Split (QS) function.",
                 kind: .signedNumber(-20...20, unit: "kHz"),
                 digits: 2, defaultValue: 5),
        MenuItem(id: "05-14", group: .general,
                 officialName: "TX TOT",
                 friendlyName: "TX time-out timer",
                 summary: "Maximum continuous transmit time before forced RX.",
                 kind: .number(0...30, unit: "min"),  // 0 = OFF
                 digits: 2, defaultValue: 0),
        MenuItem(id: "05-15", group: .general,
                 officialName: "MIC SCAN",
                 friendlyName: "Mic scan",
                 summary: "Enables auto-scan started from the microphone UP/DWN keys.",
                 kind: .toggle,
                 digits: 1, defaultValue: 1),
        MenuItem(id: "05-16", group: .general,
                 officialName: "MIC SCAN RESUME",
                 friendlyName: "Scan resume mode",
                 summary: "Whether scan pauses on a signal or resumes after 5 s.",
                 kind: .options(["PAUSE", "TIME"]),
                 digits: 1, defaultValue: 1),
        MenuItem(id: "05-17", group: .general,
                 officialName: "REF FREQ ADJ",
                 friendlyName: "Reference oscillator adjust",
                 summary: "Calibrates the master reference oscillator.",
                 kind: .signedNumber(-25...25),
                 digits: 2, defaultValue: 0),
        MenuItem(id: "05-18", group: .general,
                 officialName: "CLAR SELECT",
                 friendlyName: "Clarifier mode",
                 summary: "Whether the clarifier shifts RX, TX, or both.",
                 kind: .options(["RX", "TX", "TRX"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "05-19", group: .general,
                 officialName: "APO",
                 friendlyName: "Auto power off",
                 summary: "Powers the radio off after the selected idle time.",
                 kind: .options(["OFF", "1 h", "2 h", "4 h", "6 h", "8 h", "10 h", "12 h"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "05-20", group: .general,
                 officialName: "FAN CONTROL",
                 friendlyName: "Fan profile",
                 summary: "Normal or aggressive (contest) cooling-fan behavior.",
                 kind: .options(["NORMAL", "CONTEST"]),
                 digits: 1, defaultValue: 0),
    ]

    // MARK: - 06 MODE AM

    private static let modeAM: [MenuItem] = [
        MenuItem(id: "06-01", group: .modeAM,
                 officialName: "AM LCUT FREQ",
                 friendlyName: "AM RX low-cut frequency",
                 summary: "Low-frequency cutoff of the AM receive audio filter.",
                 kind: SharedEncoding.lcut,
                 digits: 2, defaultValue: 0),
        MenuItem(id: "06-02", group: .modeAM,
                 officialName: "AM LCUT SLOPE",
                 friendlyName: "AM low-cut slope",
                 summary: "Slope of the AM low-cut filter.",
                 kind: SharedEncoding.slope,
                 digits: 1, defaultValue: 0),
        MenuItem(id: "06-03", group: .modeAM,
                 officialName: "AM HCUT FREQ",
                 friendlyName: "AM RX high-cut frequency",
                 summary: "High-frequency cutoff of the AM receive audio filter.",
                 kind: SharedEncoding.hcut,
                 digits: 2, defaultValue: 0),
        MenuItem(id: "06-04", group: .modeAM,
                 officialName: "AM HCUT SLOPE",
                 friendlyName: "AM high-cut slope",
                 summary: "Slope of the AM high-cut filter.",
                 kind: SharedEncoding.slope,
                 digits: 1, defaultValue: 0),
        MenuItem(id: "06-05", group: .modeAM,
                 officialName: "AM MIC SELECT",
                 friendlyName: "AM audio input",
                 summary: "Front MIC jack or rear RTTY/DATA jack as AM TX audio source.",
                 kind: SharedEncoding.micSelect,
                 digits: 1, defaultValue: 0),
        MenuItem(id: "06-06", group: .modeAM,
                 officialName: "AM OUT LEVEL",
                 friendlyName: "AM rear output level",
                 summary: "RX audio level on the RTTY/DATA jack in AM mode.",
                 kind: SharedEncoding.level100,
                 digits: 3, defaultValue: 50),
        MenuItem(id: "06-07", group: .modeAM,
                 officialName: "AM PTT SELECT",
                 friendlyName: "AM PTT source",
                 summary: "PTT control line used for AM transmit.",
                 kind: SharedEncoding.pttSelect,
                 digits: 1, defaultValue: 0),
    ]

    // MARK: - 07 MODE CW

    private static let modeCW: [MenuItem] = [
        MenuItem(id: "07-01", group: .modeCW,
                 officialName: "CW LCUT FREQ",
                 friendlyName: "CW RX low-cut frequency",
                 summary: "Low-frequency cutoff of the CW receive audio filter.",
                 kind: SharedEncoding.lcut,
                 digits: 2, defaultValue: 4),  // 250 Hz
        MenuItem(id: "07-02", group: .modeCW,
                 officialName: "CW LCUT SLOPE",
                 friendlyName: "CW low-cut slope",
                 summary: "Slope of the CW low-cut filter.",
                 kind: SharedEncoding.slope,
                 digits: 1, defaultValue: 1),
        MenuItem(id: "07-03", group: .modeCW,
                 officialName: "CW HCUT FREQ",
                 friendlyName: "CW RX high-cut frequency",
                 summary: "High-frequency cutoff of the CW receive audio filter.",
                 kind: SharedEncoding.hcut,
                 digits: 2, defaultValue: 11),  // 1200 Hz
        MenuItem(id: "07-04", group: .modeCW,
                 officialName: "CW HCUT SLOPE",
                 friendlyName: "CW high-cut slope",
                 summary: "Slope of the CW high-cut filter.",
                 kind: SharedEncoding.slope,
                 digits: 1, defaultValue: 1),
        MenuItem(id: "07-05", group: .modeCW,
                 officialName: "CW OUT LEVEL",
                 friendlyName: "CW rear output level",
                 summary: "RX audio level on the RTTY/DATA jack in CW mode.",
                 kind: SharedEncoding.level100,
                 digits: 3, defaultValue: 50),
        MenuItem(id: "07-06", group: .modeCW,
                 officialName: "CW AUTO MODE",
                 friendlyName: "CW keying in SSB",
                 summary: "Allows CW keying while operating SSB (off / 50 MHz only / all bands).",
                 kind: .options(["OFF", "50M", "ON"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "07-07", group: .modeCW,
                 officialName: "CW BFO",
                 friendlyName: "CW carrier side",
                 summary: "CW carrier injection side (affects MD mode reporting).",
                 kind: .options(["USB", "LSB", "AUTO"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "07-08", group: .modeCW,
                 officialName: "CW BK-IN TYPE",
                 friendlyName: "Break-in type",
                 summary: "Semi or full (QSK) break-in.",
                 kind: .options(["SEMI", "FULL"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "07-09", group: .modeCW,
                 officialName: "CW BK-IN DELAY",
                 friendlyName: "Semi break-in delay",
                 summary: "RX recovery delay after keying in semi break-in (10 ms steps).",
                 kind: .number(30...3000, step: 10, unit: "ms"),
                 digits: 4, defaultValue: 200),
        MenuItem(id: "07-10", group: .modeCW,
                 officialName: "CW WAVE SHAPE",
                 friendlyName: "Keying envelope",
                 summary: "CW carrier rise/fall time.",
                 kind: .options(["(unused)", "2 ms", "4 ms"]),  // wire is 1-based: 1 = 2 ms, 2 = 4 ms
                 digits: 1, defaultValue: 2),
        MenuItem(id: "07-11", group: .modeCW,
                 officialName: "CW FREQ DISPLAY",
                 friendlyName: "CW frequency display",
                 summary: "Displays carrier frequency or pitch-offset frequency in CW.",
                 kind: .options(["FREQ", "PITCH"]),
                 digits: 1, defaultValue: 1),
        MenuItem(id: "07-12", group: .modeCW,
                 officialName: "PC KEYING",
                 friendlyName: "PC CW keying line",
                 summary: "Keying source for computer CW (off / DAKY / RTS / DTR).",
                 kind: .options(["OFF", "DAKY", "RTS", "DTR"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "07-13", group: .modeCW,
                 officialName: "QSK DELAY TIME",
                 friendlyName: "QSK TX delay",
                 summary: "Delay before the carrier is transmitted in full break-in.",
                 kind: .options(["15 ms", "20 ms", "25 ms", "30 ms"]),
                 digits: 1, defaultValue: 0),
    ]

    // MARK: - 08 MODE DATA

    private static let modeDATA: [MenuItem] = [
        MenuItem(id: "08-01", group: .modeDATA,
                 officialName: "DATA MODE",
                 friendlyName: "Data scheme",
                 summary: "Operating scheme in DATA mode: PSK or other AFSK modes.",
                 kind: .options(["PSK", "OTHERS"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "08-02", group: .modeDATA,
                 officialName: "PSK TONE",
                 friendlyName: "PSK tone frequency",
                 summary: "Audio tone frequency used for PSK.",
                 kind: .options(["1000 Hz", "1500 Hz", "2000 Hz"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "08-03", group: .modeDATA,
                 officialName: "OTHER DISP",
                 friendlyName: "Data display offset",
                 summary: "Display frequency offset in DATA (OTHERS) mode, 10 Hz steps.",
                 kind: .signedNumber(-3000...3000, step: 10, unit: "Hz"),
                 digits: 4, defaultValue: 0),
        MenuItem(id: "08-04", group: .modeDATA,
                 officialName: "OTHER SHIFT",
                 friendlyName: "Data carrier point",
                 summary: "Carrier point offset in DATA (OTHERS) mode, 10 Hz steps.",
                 kind: .signedNumber(-3000...3000, step: 10, unit: "Hz"),
                 digits: 4, defaultValue: 0),
        MenuItem(id: "08-05", group: .modeDATA,
                 officialName: "DATA LCUT FREQ",
                 friendlyName: "Data RX low-cut frequency",
                 summary: "Low-frequency cutoff of the DATA receive audio filter.",
                 kind: SharedEncoding.lcut,
                 digits: 2, defaultValue: 5),  // 300 Hz
        MenuItem(id: "08-06", group: .modeDATA,
                 officialName: "DATA LCUT SLOPE",
                 friendlyName: "Data low-cut slope",
                 summary: "Slope of the DATA low-cut filter.",
                 kind: SharedEncoding.slope,
                 digits: 1, defaultValue: 1),
        MenuItem(id: "08-07", group: .modeDATA,
                 officialName: "DATA HCUT FREQ",
                 friendlyName: "Data RX high-cut frequency",
                 summary: "High-frequency cutoff of the DATA receive audio filter.",
                 kind: SharedEncoding.hcut,
                 digits: 2, defaultValue: 47),  // 3000 Hz
        MenuItem(id: "08-08", group: .modeDATA,
                 officialName: "DATA HCUT SLOPE",
                 friendlyName: "Data high-cut slope",
                 summary: "Slope of the DATA high-cut filter.",
                 kind: SharedEncoding.slope,
                 digits: 1, defaultValue: 1),
        MenuItem(id: "08-09", group: .modeDATA,
                 officialName: "DATA IN SELECT",
                 friendlyName: "Data audio input",
                 summary: "Front MIC jack or rear RTTY/DATA jack as DATA input.",
                 kind: SharedEncoding.micSelect,
                 digits: 1, defaultValue: 1),
        MenuItem(id: "08-10", group: .modeDATA,
                 officialName: "DATA PTT SELECT",
                 friendlyName: "Data PTT source",
                 summary: "PTT control line used for DATA transmit.",
                 kind: SharedEncoding.pttSelect,
                 digits: 1, defaultValue: 0),
        MenuItem(id: "08-11", group: .modeDATA,
                 officialName: "DATA OUT LEVEL",
                 friendlyName: "Data output level",
                 summary: "Audio output level on the rear jack for data operation.",
                 kind: SharedEncoding.level100,
                 digits: 3, defaultValue: 50),
        MenuItem(id: "08-12", group: .modeDATA,
                 officialName: "DATA BFO",
                 friendlyName: "Data carrier side",
                 summary: "DATA carrier injection side (affects MD mode reporting).",
                 kind: .options(["USB", "LSB"]),
                 digits: 1, defaultValue: 1),
    ]

    // MARK: - 09 MODE FM

    private static let modeFM: [MenuItem] = [
        MenuItem(id: "09-01", group: .modeFM,
                 officialName: "FM MIC SELECT",
                 friendlyName: "FM audio input",
                 summary: "Front MIC jack or rear RTTY/DATA jack as FM TX audio source.",
                 kind: SharedEncoding.micSelect,
                 digits: 1, defaultValue: 0),
        MenuItem(id: "09-02", group: .modeFM,
                 officialName: "FM OUT LEVEL",
                 friendlyName: "FM rear output level",
                 summary: "RX audio level on the RTTY/DATA jack in FM mode.",
                 kind: SharedEncoding.level100,
                 digits: 3, defaultValue: 50),
        MenuItem(id: "09-03", group: .modeFM,
                 officialName: "PKT PTT SELECT",
                 friendlyName: "Packet PTT source",
                 summary: "PTT control line used for FM packet transmit.",
                 kind: SharedEncoding.pttSelect,
                 digits: 1, defaultValue: 0),
        MenuItem(id: "09-04", group: .modeFM,
                 officialName: "RPT SHIFT 28MHz",
                 friendlyName: "28 MHz repeater offset",
                 summary: "Repeater shift amount on the 28 MHz band (10 kHz steps).",
                 kind: .number(0...1000, step: 10, unit: "kHz"),
                 digits: 4, defaultValue: 100),
        MenuItem(id: "09-05", group: .modeFM,
                 officialName: "RPT SHIFT 50MHz",
                 friendlyName: "50 MHz repeater offset",
                 summary: "Repeater shift amount on the 50 MHz band (10 kHz steps).",
                 kind: .number(0...4000, step: 10, unit: "kHz"),
                 digits: 4, defaultValue: 1000),
        MenuItem(id: "09-06", group: .modeFM,
                 officialName: "DCS POLARITY",
                 friendlyName: "DCS polarity",
                 summary: "Normal/inverted DCS code phase for TX and RX.",
                 kind: .options(["Tn-Rn", "Tn-Riv", "Tiv-Rn", "Tiv-Riv"]),
                 digits: 1, defaultValue: 0),
    ]

    // MARK: - 10 MODE RTTY

    private static let modeRTTY: [MenuItem] = [
        MenuItem(id: "10-01", group: .modeRTTY,
                 officialName: "RTTY LCUT FREQ",
                 friendlyName: "RTTY RX low-cut frequency",
                 summary: "Low-frequency cutoff of the RTTY receive audio filter.",
                 kind: SharedEncoding.lcut,
                 digits: 2, defaultValue: 5),  // 300 Hz
        MenuItem(id: "10-02", group: .modeRTTY,
                 officialName: "RTTY LCUT SLOPE",
                 friendlyName: "RTTY low-cut slope",
                 summary: "Slope of the RTTY low-cut filter.",
                 kind: SharedEncoding.slope,
                 digits: 1, defaultValue: 1),
        MenuItem(id: "10-03", group: .modeRTTY,
                 officialName: "RTTY HCUT FREQ",
                 friendlyName: "RTTY RX high-cut frequency",
                 summary: "High-frequency cutoff of the RTTY receive audio filter.",
                 kind: SharedEncoding.hcut,
                 digits: 2, defaultValue: 47),  // 3000 Hz
        MenuItem(id: "10-04", group: .modeRTTY,
                 officialName: "RTTY HCUT SLOPE",
                 friendlyName: "RTTY high-cut slope",
                 summary: "Slope of the RTTY high-cut filter.",
                 kind: SharedEncoding.slope,
                 digits: 1, defaultValue: 1),
        MenuItem(id: "10-05", group: .modeRTTY,
                 officialName: "RTTY SHIFT PORT",
                 friendlyName: "FSK shift input",
                 summary: "Input line used for FSK shift keying.",
                 kind: .options(["SHIFT", "DTR", "RTS"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "10-06", group: .modeRTTY,
                 officialName: "RTTY POLARITY-R",
                 friendlyName: "RX shift polarity",
                 summary: "Mark/space shift direction on receive.",
                 kind: .options(["NOR", "REV"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "10-07", group: .modeRTTY,
                 officialName: "RTTY POLARITY-T",
                 friendlyName: "TX shift polarity",
                 summary: "Mark/space shift direction on transmit.",
                 kind: .options(["NOR", "REV"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "10-08", group: .modeRTTY,
                 officialName: "RTTY OUT LEVEL",
                 friendlyName: "RTTY output level",
                 summary: "Audio output level on the rear jack in RTTY mode.",
                 kind: SharedEncoding.level100,
                 digits: 3, defaultValue: 50),
        MenuItem(id: "10-09", group: .modeRTTY,
                 officialName: "RTTY SHIFT FREQ",
                 friendlyName: "RTTY shift width",
                 summary: "FSK shift width.",
                 kind: .options(["170 Hz", "200 Hz", "425 Hz", "850 Hz"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "10-10", group: .modeRTTY,
                 officialName: "RTTY MARK FREQ",
                 friendlyName: "RTTY mark frequency",
                 summary: "Mark tone frequency.",
                 kind: .options(["1275 Hz", "2125 Hz"]),
                 digits: 1, defaultValue: 1),
        MenuItem(id: "10-11", group: .modeRTTY,
                 officialName: "RTTY BFO",
                 friendlyName: "RTTY carrier side",
                 summary: "RTTY carrier injection side (affects MD mode reporting).",
                 kind: .options(["USB", "LSB"]),
                 digits: 1, defaultValue: 1),
    ]

    // MARK: - 11 MODE SSB

    private static let modeSSB: [MenuItem] = [
        MenuItem(id: "11-01", group: .modeSSB,
                 officialName: "SSB LCUT FREQ",
                 friendlyName: "SSB RX low-cut frequency",
                 summary: "Low-frequency cutoff of the SSB receive audio filter.",
                 kind: SharedEncoding.lcut,
                 digits: 2, defaultValue: 1),  // 100 Hz
        MenuItem(id: "11-02", group: .modeSSB,
                 officialName: "SSB LCUT SLOPE",
                 friendlyName: "SSB low-cut slope",
                 summary: "Slope of the SSB low-cut filter.",
                 kind: SharedEncoding.slope,
                 digits: 1, defaultValue: 0),
        MenuItem(id: "11-03", group: .modeSSB,
                 officialName: "SSB HCUT FREQ",
                 friendlyName: "SSB RX high-cut frequency",
                 summary: "High-frequency cutoff of the SSB receive audio filter.",
                 kind: SharedEncoding.hcut,
                 digits: 2, defaultValue: 47),  // 3000 Hz
        MenuItem(id: "11-04", group: .modeSSB,
                 officialName: "SSB HCUT SLOPE",
                 friendlyName: "SSB high-cut slope",
                 summary: "Slope of the SSB high-cut filter.",
                 kind: SharedEncoding.slope,
                 digits: 1, defaultValue: 0),
        MenuItem(id: "11-05", group: .modeSSB,
                 officialName: "SSB MIC SELECT",
                 friendlyName: "SSB audio input",
                 summary: "Front MIC jack or rear RTTY/DATA jack as SSB TX audio source.",
                 kind: SharedEncoding.micSelect,
                 digits: 1, defaultValue: 0),
        MenuItem(id: "11-06", group: .modeSSB,
                 officialName: "SSB OUT LEVEL",
                 friendlyName: "SSB rear output level",
                 summary: "RX audio level on the RTTY/DATA jack in SSB mode.",
                 kind: SharedEncoding.level100,
                 digits: 3, defaultValue: 50),
        MenuItem(id: "11-07", group: .modeSSB,
                 officialName: "SSB BFO",
                 friendlyName: "SSB carrier side",
                 summary: "SSB carrier injection side; AUTO = LSB ≤7 MHz, USB ≥10 MHz.",
                 kind: .options(["USB", "LSB", "AUTO"]),
                 digits: 1, defaultValue: 2),
        MenuItem(id: "11-08", group: .modeSSB,
                 officialName: "SSB PTT SELECT",
                 friendlyName: "SSB PTT source",
                 summary: "PTT control line used for SSB transmit.",
                 kind: SharedEncoding.pttSelect,
                 digits: 1, defaultValue: 0),
        MenuItem(id: "11-09", group: .modeSSB,
                 officialName: "SSB TX BPF",
                 friendlyName: "SSB TX bandwidth",
                 summary: "DSP transmit band-pass filter range in SSB.",
                 kind: .options(["100-3000 Hz", "100-2900 Hz", "200-2800 Hz",
                                 "300-2700 Hz", "400-2600 Hz"]),
                 digits: 1, defaultValue: 3),
    ]

    // MARK: - 12 RX DSP

    private static let rxDSP: [MenuItem] = [
        MenuItem(id: "12-01", group: .rxDSP,
                 officialName: "APF WIDTH",
                 friendlyName: "Audio peak filter width",
                 summary: "Bandwidth of the CW audio peak filter.",
                 kind: .options(["NARROW", "MEDIUM", "WIDE"]),
                 digits: 1, defaultValue: 1),
        MenuItem(id: "12-02", group: .rxDSP,
                 officialName: "CONTOUR LEVEL",
                 friendlyName: "Contour gain",
                 summary: "Gain/attenuation depth of the contour circuit.",
                 kind: .signedNumber(-40...20),
                 digits: 2, defaultValue: -15),
        MenuItem(id: "12-03", group: .rxDSP,
                 officialName: "CONTOUR WIDTH",
                 friendlyName: "Contour Q",
                 summary: "Bandwidth (Q) of the contour circuit.",
                 kind: .number(1...11),
                 digits: 2, defaultValue: 10),
        MenuItem(id: "12-04", group: .rxDSP,
                 officialName: "IF NOTCH WIDTH",
                 friendlyName: "IF notch width",
                 summary: "Attenuation bandwidth of the DSP IF notch filter.",
                 kind: .options(["NARROW", "WIDE"]),
                 digits: 1, defaultValue: 1),
    ]

    // MARK: - 13 SCOPE

    private static let scope: [MenuItem] = [
        MenuItem(id: "13-01", group: .scope,
                 officialName: "SCP START CYCLE",
                 friendlyName: "Scope sweep interval",
                 summary: "Auto-repeat interval of the spectrum-scope sweep.",
                 kind: .options(["OFF", "3 s", "5 s", "10 s"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "13-02", group: .scope,
                 officialName: "SCP SPAN FREQ",
                 friendlyName: "Scope span",
                 summary: "Frequency span of the spectrum scope.",
                 kind: .options(["37.5 kHz", "75 kHz", "150 kHz", "375 kHz", "750 kHz"]),
                 // Hardware-verified: the radio answers 2 digits ("03"),
                 // not 1 as the CAT book table suggests.
                 digits: 2, defaultValue: 4),
    ]

    // MARK: - 14 TUNING

    private static let tuning: [MenuItem] = [
        MenuItem(id: "14-01", group: .tuning,
                 officialName: "QUICK DIAL",
                 friendlyName: "MULTI knob step",
                 summary: "MULTI-knob tuning step in SSB/CW/RTTY/DATA.",
                 kind: .options(["50 kHz", "100 kHz", "500 kHz"]),
                 digits: 1, defaultValue: 2),
        MenuItem(id: "14-02", group: .tuning,
                 officialName: "SSB DIAL STEP",
                 friendlyName: "SSB dial step",
                 summary: "Main dial step in SSB.",
                 kind: .options(["2 Hz", "5 Hz", "10 Hz"]),
                 digits: 1, defaultValue: 2),
        MenuItem(id: "14-03", group: .tuning,
                 officialName: "AM DIAL STEP",
                 friendlyName: "AM dial step",
                 summary: "Main dial step in AM.",
                 kind: .options(["10 Hz", "100 Hz"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "14-04", group: .tuning,
                 officialName: "FM DIAL STEP",
                 friendlyName: "FM dial step",
                 summary: "Main dial step in FM.",
                 kind: .options(["10 Hz", "100 Hz"]),
                 digits: 1, defaultValue: 1),
        MenuItem(id: "14-05", group: .tuning,
                 officialName: "DIAL STEP",
                 friendlyName: "CW/RTTY/DATA dial step",
                 summary: "Main dial step (non-SSB/AM/FM modes).",
                 kind: .options(["2 Hz", "5 Hz", "10 Hz"]),
                 digits: 1, defaultValue: 1),
        MenuItem(id: "14-06", group: .tuning,
                 officialName: "AM CH STEP",
                 friendlyName: "AM channel step",
                 summary: "MULTI-knob / mic UP-DWN channel step in AM.",
                 kind: .options(["2.5 kHz", "5 kHz", "9 kHz", "10 kHz", "12.5 kHz", "25 kHz"]),
                 digits: 1, defaultValue: 0),  // manual ambiguity: summary table says 5 kHz
        MenuItem(id: "14-07", group: .tuning,
                 officialName: "FM CH STEP",
                 friendlyName: "FM channel step",
                 summary: "MULTI-knob / mic UP-DWN channel step in FM.",
                 kind: .options(["5 kHz", "6.25 kHz", "10 kHz", "12.5 kHz",
                                 "15 kHz", "20 kHz", "25 kHz"]),
                 digits: 1, defaultValue: 0),
    ]

    // MARK: - 15 TX AUDIO

    private static let txAudio: [MenuItem] = [
        MenuItem(id: "15-01", group: .txAudio,
                 officialName: "EQ1 FREQ",
                 friendlyName: "EQ low band frequency",
                 summary: "Center frequency of the low EQ band.",
                 kind: eq1Freq,
                 digits: 2, defaultValue: 0),
        MenuItem(id: "15-02", group: .txAudio,
                 officialName: "EQ1 LEVEL",
                 friendlyName: "EQ low band gain",
                 summary: "Gain of the low EQ band.",
                 kind: .signedNumber(-20...10, unit: "dB"),
                 digits: 2, defaultValue: 5),
        MenuItem(id: "15-03", group: .txAudio,
                 officialName: "EQ1 BWTH",
                 friendlyName: "EQ low band Q",
                 summary: "Bandwidth (Q) of the low EQ band.",
                 kind: .number(1...10),
                 digits: 2, defaultValue: 10),
        MenuItem(id: "15-04", group: .txAudio,
                 officialName: "EQ2 FREQ",
                 friendlyName: "EQ mid band frequency",
                 summary: "Center frequency of the mid EQ band.",
                 kind: eq2Freq,
                 digits: 2, defaultValue: 0),
        MenuItem(id: "15-05", group: .txAudio,
                 officialName: "EQ2 LEVEL",
                 friendlyName: "EQ mid band gain",
                 summary: "Gain of the mid EQ band.",
                 kind: .signedNumber(-20...10, unit: "dB"),
                 digits: 2, defaultValue: 5),
        MenuItem(id: "15-06", group: .txAudio,
                 officialName: "EQ2 BWTH",
                 friendlyName: "EQ mid band Q",
                 summary: "Bandwidth (Q) of the mid EQ band.",
                 kind: .number(1...10),
                 digits: 2, defaultValue: 10),
        MenuItem(id: "15-07", group: .txAudio,
                 officialName: "EQ3 FREQ",
                 friendlyName: "EQ high band frequency",
                 summary: "Center frequency of the high EQ band.",
                 kind: eq3Freq,
                 digits: 2, defaultValue: 0),
        MenuItem(id: "15-08", group: .txAudio,
                 officialName: "EQ3 LEVEL",
                 friendlyName: "EQ high band gain",
                 summary: "Gain of the high EQ band.",
                 kind: .signedNumber(-20...10, unit: "dB"),
                 digits: 2, defaultValue: 5),
        MenuItem(id: "15-09", group: .txAudio,
                 officialName: "EQ3 BWTH",
                 friendlyName: "EQ high band Q",
                 summary: "Bandwidth (Q) of the high EQ band.",
                 kind: .number(1...10),
                 digits: 2, defaultValue: 10),
        MenuItem(id: "15-10", group: .txAudio,
                 officialName: "P-EQ1 FREQ",
                 friendlyName: "Proc EQ low frequency",
                 summary: "Low EQ band center with speech processor on.",
                 kind: eq1Freq,
                 digits: 2, defaultValue: 2),  // 200 Hz
        MenuItem(id: "15-11", group: .txAudio,
                 officialName: "P-EQ1 LEVEL",
                 friendlyName: "Proc EQ low gain",
                 summary: "Low EQ band gain with speech processor on.",
                 kind: .signedNumber(-20...10, unit: "dB"),
                 digits: 2, defaultValue: 0),
        MenuItem(id: "15-12", group: .txAudio,
                 officialName: "P-EQ1 BWTH",
                 friendlyName: "Proc EQ low Q",
                 summary: "Low EQ band Q with speech processor on.",
                 kind: .number(1...10),
                 digits: 2, defaultValue: 2),
        MenuItem(id: "15-13", group: .txAudio,
                 officialName: "P-EQ2 FREQ",
                 friendlyName: "Proc EQ mid frequency",
                 summary: "Mid EQ band center with speech processor on.",
                 kind: eq2Freq,
                 digits: 2, defaultValue: 2),  // 800 Hz
        MenuItem(id: "15-14", group: .txAudio,
                 officialName: "P-EQ2 LEVEL",
                 friendlyName: "Proc EQ mid gain",
                 summary: "Mid EQ band gain with speech processor on.",
                 kind: .signedNumber(-20...10, unit: "dB"),
                 digits: 2, defaultValue: 0),
        MenuItem(id: "15-15", group: .txAudio,
                 officialName: "P-EQ2 BWTH",
                 friendlyName: "Proc EQ mid Q",
                 summary: "Mid EQ band Q with speech processor on.",
                 kind: .number(1...10),
                 digits: 2, defaultValue: 1),
        MenuItem(id: "15-16", group: .txAudio,
                 officialName: "P-EQ3 FREQ",
                 friendlyName: "Proc EQ high frequency",
                 summary: "High EQ band center with speech processor on.",
                 kind: eq3Freq,
                 digits: 2, defaultValue: 7),  // 2100 Hz
        MenuItem(id: "15-17", group: .txAudio,
                 officialName: "P-EQ3 LEVEL",
                 friendlyName: "Proc EQ high gain",
                 summary: "High EQ band gain with speech processor on.",
                 kind: .signedNumber(-20...10, unit: "dB"),
                 digits: 2, defaultValue: 0),
        MenuItem(id: "15-18", group: .txAudio,
                 officialName: "P-EQ3 BWTH",
                 friendlyName: "Proc EQ high Q",
                 summary: "High EQ band Q with speech processor on.",
                 kind: .number(1...10),
                 digits: 2, defaultValue: 1),
    ]

    // MARK: - 16 TX GENERAL

    private static let txGeneral: [MenuItem] = [
        MenuItem(id: "16-01", group: .txGeneral,
                 officialName: "HF SSB PWR",
                 friendlyName: "HF SSB power",
                 summary: "Max TX power for SSB on HF.",
                 kind: .number(5...100, unit: "W"),
                 digits: 3, defaultValue: 100),
        MenuItem(id: "16-02", group: .txGeneral,
                 officialName: "HF AM PWR",
                 friendlyName: "HF AM power",
                 summary: "Max TX (carrier) power for AM on HF.",
                 kind: .number(5...40, unit: "W"),
                 digits: 3, defaultValue: 25),
        MenuItem(id: "16-03", group: .txGeneral,
                 officialName: "HF PWR",
                 friendlyName: "HF power (CW/data/FM)",
                 summary: "Max TX power on HF for all other modes.",
                 kind: .number(5...100, unit: "W"),
                 digits: 3, defaultValue: 100),
        MenuItem(id: "16-04", group: .txGeneral,
                 officialName: "50M SSB PWR",
                 friendlyName: "6 m SSB power",
                 summary: "Max TX power for SSB on 50 MHz.",
                 kind: .number(5...100, unit: "W"),
                 digits: 3, defaultValue: 100),
        MenuItem(id: "16-05", group: .txGeneral,
                 officialName: "50M AM PWR",
                 friendlyName: "6 m AM power",
                 summary: "Max TX (carrier) power for AM on 50 MHz.",
                 kind: .number(5...40, unit: "W"),
                 digits: 3, defaultValue: 25),
        MenuItem(id: "16-06", group: .txGeneral,
                 officialName: "50M PWR",
                 friendlyName: "6 m power (CW/data/FM)",
                 summary: "Max TX power on 50 MHz for all other modes.",
                 kind: .number(5...100, unit: "W"),
                 digits: 3, defaultValue: 100),
        MenuItem(id: "16-07", group: .txGeneral,
                 officialName: "SSB MIC GAIN",
                 friendlyName: "SSB mic gain",
                 summary: "Microphone gain in SSB mode.",
                 kind: SharedEncoding.level100,
                 digits: 3, defaultValue: 30),  // manual ambiguity: summary table says 50
        MenuItem(id: "16-08", group: .txGeneral,
                 officialName: "AM MIC GAIN",
                 friendlyName: "AM mic gain",
                 summary: "Microphone gain in AM mode.",
                 kind: SharedEncoding.level100,
                 digits: 3, defaultValue: 30),  // manual ambiguity: summary table says 50
        MenuItem(id: "16-09", group: .txGeneral,
                 officialName: "FM MIC GAIN",
                 friendlyName: "FM mic gain",
                 summary: "Microphone gain in FM mode.",
                 kind: SharedEncoding.level100,
                 digits: 3, defaultValue: 50),
        MenuItem(id: "16-10", group: .txGeneral,
                 officialName: "DATA MIC GAIN",
                 friendlyName: "Data AFSK input gain",
                 summary: "Input level from the TNC to the AFSK modulator.",
                 kind: SharedEncoding.level100,
                 digits: 3, defaultValue: 50),
        MenuItem(id: "16-11", group: .txGeneral,
                 officialName: "SSB DATA GAIN",
                 friendlyName: "SSB rear input gain",
                 summary: "Rear-jack input level when SSB MIC SELECT = REAR.",
                 kind: SharedEncoding.level100,
                 digits: 3, defaultValue: 50),
        MenuItem(id: "16-12", group: .txGeneral,
                 officialName: "AM DATA GAIN",
                 friendlyName: "AM rear input gain",
                 summary: "Rear-jack input level when AM MIC SELECT = REAR.",
                 kind: SharedEncoding.level100,
                 digits: 3, defaultValue: 50),
        MenuItem(id: "16-13", group: .txGeneral,
                 officialName: "FM DATA GAIN",
                 friendlyName: "FM rear input gain",
                 summary: "Rear-jack input level when FM MIC SELECT = REAR.",
                 kind: SharedEncoding.level100,
                 digits: 3, defaultValue: 50),
        MenuItem(id: "16-14", group: .txGeneral,
                 officialName: "DATA DATA GAIN",
                 friendlyName: "Data rear input gain",
                 summary: "Rear-jack input level when DATA IN SELECT = REAR.",
                 kind: SharedEncoding.level100,
                 digits: 3, defaultValue: 50),
        MenuItem(id: "16-15", group: .txGeneral,
                 officialName: "TUNER SELECT",
                 friendlyName: "Tuner/amp selection",
                 summary: "Selects the attached tuner (FC-40/FC-50), ATAS antenna, or linear-amp control on the TUN/LIN jack. Required for `AC002;` tune to work.",
                 kind: .options(["OFF", "EXTERNAL", "ATAS", "LAMP"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "16-16", group: .txGeneral,
                 officialName: "VOX SELECT",
                 friendlyName: "VOX source",
                 summary: "VOX triggers from the mic or from rear-jack data audio.",
                 kind: .options(["MIC", "DATA"]),
                 digits: 1, defaultValue: 0),
        MenuItem(id: "16-17", group: .txGeneral,
                 officialName: "VOX GAIN",
                 friendlyName: "VOX gain",
                 summary: "Sensitivity of the VOX circuit (also via `VG` command).",
                 kind: SharedEncoding.level100,
                 digits: 3, defaultValue: 50),
        MenuItem(id: "16-18", group: .txGeneral,
                 officialName: "VOX DELAY",
                 friendlyName: "VOX delay",
                 summary: "Hang time before returning to RX (10 ms steps; also via `VD`).",
                 kind: .number(30...3000, step: 10, unit: "ms"),
                 digits: 4, defaultValue: 500),
        MenuItem(id: "16-19", group: .txGeneral,
                 officialName: "ANTI VOX GAIN",
                 friendlyName: "Anti-VOX gain",
                 summary: "Prevents speaker audio from tripping VOX.",
                 kind: SharedEncoding.level100,
                 digits: 3, defaultValue: 50),
        MenuItem(id: "16-20", group: .txGeneral,
                 officialName: "DATA VOX GAIN",
                 friendlyName: "Data VOX gain",
                 summary: "VOX sensitivity for data-audio input.",
                 kind: SharedEncoding.level100,
                 digits: 3, defaultValue: 50),
        MenuItem(id: "16-21", group: .txGeneral,
                 officialName: "DATA VOX DELAY",
                 friendlyName: "Data VOX delay",
                 summary: "VOX hang time for data operation.",
                 kind: .number(30...3000, step: 10, unit: "ms"),
                 digits: 4, defaultValue: 100),
        MenuItem(id: "16-22", group: .txGeneral,
                 officialName: "ANTI DVOX GAIN",
                 friendlyName: "Data anti-VOX gain",
                 summary: "Prevents received data audio from tripping data VOX.",
                 kind: SharedEncoding.level100,
                 digits: 3, defaultValue: 0),
        MenuItem(id: "16-23", group: .txGeneral,
                 officialName: "EMERGENCY FREQ",
                 friendlyName: "Alaska emergency channel",
                 summary: "Enables TX/RX on 5167.5 kHz (Alaska emergency use only).",
                 kind: .toggle,
                 digits: 1, defaultValue: 0),
    ]

    // MARK: - 17 RESET

    private static let reset: [MenuItem] = [
        MenuItem(id: "17-01", group: .reset,
                 officialName: "RESET",
                 friendlyName: "Radio reset",
                 summary: "Performs a reset: ALL (factory, clears memories), DATA (clears memories only), or FUNC (menu/function keys only).",
                 kind: .options(["ALL", "DATA", "FUNC"]),
                 digits: 1, defaultValue: 0,
                 isAction: true),
    ]

    // MARK: - 18 VERSION

    private static let version: [MenuItem] = [
        MenuItem(id: "18-01", group: .version,
                 officialName: "MAIN VERSION",
                 friendlyName: "Main firmware version",
                 summary: "Displays the main CPU firmware version.",
                 kind: .number(0...9999),
                 digits: 4, defaultValue: 0,
                 isWritable: false),
        MenuItem(id: "18-02", group: .version,
                 officialName: "DSP VERSION",
                 friendlyName: "DSP firmware version",
                 summary: "Displays the DSP firmware version.",
                 kind: .number(0...9999),
                 digits: 4, defaultValue: 0,
                 isWritable: false),
        MenuItem(id: "18-03", group: .version,
                 officialName: "LCD VERSION",
                 friendlyName: "LCD firmware version",
                 summary: "Displays the front-panel LCD firmware version.",
                 kind: .number(0...9999),
                 digits: 4, defaultValue: 0,
                 isWritable: false),
    ]
}
